function run_wrappers

wrapper_brain_bss_logdet
wrapper_bss_logdet
wrapper_bss_nuclear
wrapper_multigraph_bss_logdet
wrapper_multigraph_bss_nuclear_direct
wrapper_singlegraph_bss_logdet
wrapper_singlegraph_bss_logdet_knownx

end
